name: Deploy to S3

on:
  push:
    branches:
      - main  # Triggers the workflow whenever you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Pulls your code from the repo

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip install awscli

      - name: Sync files to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync . s3://bamidele-auto-dealer --exclude ".git/*" --delete

